[tool.poetry]
name = "wordle-back"
version = "0.1.0"
description = ""
authors = ["tkin91e55 <tkingkwun@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
